#!/usr/bin/env python3
"""Deterministic publisher for agent-skills.

Three modes, all driven by publish/policy.yml:

  --dry-run   report exactly what would change, write nothing   (default)
  --apply     write generated skills only
  --check     fail if public output has drifted from policy+source

Public-authored skills are never generated. That is enforced structurally: `_generated_names()`
is the only source of write targets, and `_assert_writable()` re-checks every path before a write.
"""
from __future__ import annotations
import argparse, difflib, hashlib, os, re, sys
import yaml
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from transforms import apply_all

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
POLICY = os.path.join(ROOT, "publish", "policy.yml")
LOCK = os.path.join(ROOT, "publish", "generated.lock")

# --- privacy gate: explicit, narrow, and NOT a proof of absence -------------------------
SECRET_PATTERNS = [
    (r"/Users/courtneyrobertson", "private absolute home path"),
    (r"\bCourtney\b", "personal name not covered by policy"),
    (r"\b2nd Brain\b", "private vault name"),
    (r"\bcourtneyr\.dev\b", "private domain"),
    (r"(?i)\b(api[_-]?key|secret[_-]?key|access[_-]?token|bearer)\b\s*[:=]\s*\S+", "credential-shaped assignment"),
    (r"-----BEGIN [A-Z ]*PRIVATE KEY-----", "private key block"),
    (r"\bgh[pousr]_[A-Za-z0-9]{16,}", "GitHub token"),
    (r"\bsk-[A-Za-z0-9]{20,}", "API key"),
    (r"<!--\s*private\s*-->", "explicit private marker"),
]

class Failure(Exception): pass

def load_policy(path=POLICY):
    with open(path) as f:
        pol = yaml.safe_load(f)
    for name, spec in pol["skills"].items():
        if spec.get("mode") not in ("generated", "public-authored"):
            raise Failure(f"policy: {name} has no valid mode (fail closed)")
    return pol

def canonical_root(pol):
    raw = pol["canonical_root"]
    m = re.match(r"\$\{(\w+):-(.+)\}", raw)
    if m:
        raw = os.environ.get(m.group(1)) or m.group(2)
    return os.path.expanduser(raw)

def _generated_names(pol):
    return sorted(n for n, s in pol["skills"].items() if s["mode"] == "generated")

def _public_authored_names(pol):
    return sorted(n for n, s in pol["skills"].items() if s["mode"] == "public-authored")

def _assert_writable(pol, name):
    """Structural guard. Called immediately before every write."""
    if pol["skills"][name]["mode"] != "generated":
        raise Failure(f"REFUSED: {name} is {pol['skills'][name]['mode']}; generator must never write it")

def public_path(pol, name):
    return os.path.join(ROOT, pol["public_root"], name, "SKILL.md")

def source_path(pol, name):
    spec = pol["skills"][name]
    return os.path.join(canonical_root(pol), spec.get("source", name), "SKILL.md")

def sha(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()

def write_lock(pol):
    """Record what the publisher produced, so public CI can detect hand edits to generated files
    WITHOUT needing the private canonical sources."""
    lines = ["# Generated by publish_skills.py --apply. Do not edit by hand.",
             "# sha256 of each GENERATED public SKILL.md. Public-authored skills are absent by design."]
    for name in _generated_names(pol):
        pp = public_path(pol, name)
        if os.path.exists(pp):
            lines.append(f"{name} {sha(open(pp, encoding='utf-8').read())}")
    with open(LOCK, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

def read_lock():
    if not os.path.exists(LOCK):
        return None
    out = {}
    for line in open(LOCK, encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        n, h = line.split()
        out[n] = h
    return out

def cmd_verify_public(pol):
    """CI-safe. Uses only files in this repository -- never the private canonical sources.

    Proves: every skill has a declared mode; public-authored files exist and are NOT under
    generator control; every generated artifact matches the lock recorded at publish time.
    Does NOT prove canonical drift -- that needs the private sources and stays local-only.
    """
    problems = []
    lock = read_lock()
    if lock is None:
        return _report("verify-public", ["publish/generated.lock missing -- run --apply locally"])
    for name in _public_authored_names(pol):
        if not os.path.exists(public_path(pol, name)):
            problems.append(f"{name}: public-authored file missing")
        if name in lock:
            problems.append(f"{name}: public-authored but present in generated.lock (would be overwritten)")
    for name in _generated_names(pol):
        pp = public_path(pol, name)
        if not os.path.exists(pp):
            problems.append(f"{name}: generated artifact missing"); continue
        if name not in lock:
            problems.append(f"{name}: generated but absent from lock -- republish locally"); continue
        if sha(open(pp, encoding="utf-8").read()) != lock[name]:
            problems.append(f"{name}: generated artifact edited by hand (lock mismatch)")
    problems += validate_manifest(pol)
    return _report("verify-public", problems,
                   ok=f"{len(_generated_names(pol))} generated artifacts match the lock, "
                      f"{len(_public_authored_names(pol))} public-authored protected")

def _report(label, problems, ok=""):
    if problems:
        print(f"{label}: FAIL ({len(problems)})")
        for p in problems: print("  !", p)
        return 1
    print(f"{label}: clean — {ok}")
    return 0

def privacy_scan(text, name):
    hits = [why for pat, why in SECRET_PATTERNS if re.search(pat, text)]
    return [f"{name}: {h}" for h in hits]

def render(pol, name):
    src = source_path(pol, name)
    if not os.path.exists(src):
        raise Failure(f"{name}: canonical source missing at {src}")
    spec = pol["skills"][name]
    transforms = spec.get("transforms", pol["defaults"]["transforms"])
    with open(src, encoding="utf-8") as f:
        text = f.read()
    # Declarative, per-skill line removal. Explicit substrings only -- never a heuristic.
    omit = spec.get("omit_lines_containing", [])
    if omit:
        text = "\n".join(l for l in text.split("\n") if not any(o in l for o in omit))
    out = apply_all(text, transforms)
    if not out.endswith("\n"):
        out += "\n"
    return out

def plan(pol):
    """Returns (changes, current, problems). Never writes."""
    changes, current, problems = [], [], []
    for name in _generated_names(pol):
        try:
            want = render(pol, name)
        except Failure as e:
            problems.append(str(e)); continue
        leaks = privacy_scan(want, name)
        if leaks:
            problems.extend(leaks); continue
        pp = public_path(pol, name)
        have = open(pp, encoding="utf-8").read() if os.path.exists(pp) else None
        if have == want:
            current.append(name)
        else:
            changes.append((name, have, want, pp))
    for name in _public_authored_names(pol):
        pp = public_path(pol, name)
        if not os.path.exists(pp):
            problems.append(f"{name}: public-authored file missing at {pp}")
    return changes, current, problems

def cmd_dry_run(pol, show_diff=True):
    changes, current, problems = plan(pol)
    print(f"generated considered : {len(_generated_names(pol))}")
    print(f"  already current    : {len(current)}")
    print(f"  would change/add   : {len(changes)}")
    print(f"public-authored PROTECTED (never generated): {len(_public_authored_names(pol))}")
    for n in _public_authored_names(pol):
        print(f"    skip {n}")
    if show_diff:
        for name, have, want, pp in changes:
            rel = os.path.relpath(pp, ROOT)
            a = (have or "").splitlines(keepends=True)
            print(f"\n--- would {'add' if have is None else 'change'}: {rel}")
            for line in list(difflib.unified_diff(a, want.splitlines(keepends=True),
                                                  fromfile=f"a/{rel}", tofile=f"b/{rel}"))[:40]:
                print("   " + line.rstrip("\n"))
    if problems:
        print(f"\nPROBLEMS ({len(problems)}) — publication would fail closed:")
        for p in problems: print("  !", p)
    return 1 if problems else 0

def cmd_apply(pol):
    changes, current, problems = plan(pol)
    if problems:
        print("refusing to apply; unresolved problems:")
        for p in problems: print("  !", p)
        return 1
    for name, have, want, pp in changes:
        _assert_writable(pol, name)
        os.makedirs(os.path.dirname(pp), exist_ok=True)
        with open(pp, "w", encoding="utf-8") as f:
            f.write(want)
        print(f"wrote {os.path.relpath(pp, ROOT)}")
    write_lock(pol)
    print(f"wrote {os.path.relpath(LOCK, ROOT)}")
    print(f"applied: {len(changes)} written, {len(current)} already current")
    return 0

def validate_manifest(pol):
    """Validate the hand-maintained manifest against policy. We do NOT regenerate it: it carries
    judgment (attribution, licence interpretation, private exclusion) that heuristics must not
    overwrite. The publisher only checks the facts it can derive."""
    mpath = os.path.join(ROOT, "manifest.json")
    if not os.path.exists(mpath):
        return ["manifest.json missing"]
    import json
    with open(mpath) as f:
        man = json.load(f)
    declared = {r["name"] for r in man.get("skills", []) if r.get("kind") == "vendored"}
    policied = set(pol["skills"])
    out = []
    for n in sorted(policied - declared):
        out.append(f"manifest: {n} is in policy but not declared vendored")
    for n in sorted(declared - policied):
        out.append(f"manifest: {n} declared vendored but absent from policy")
    for r in man.get("skills", []):
        if r.get("kind") == "vendored" and not r.get("redistributable", False):
            out.append(f"manifest: {r['name']} vendored but not redistributable")

    # Derivable counts must not drift. Machine-snapshot counts are NOT checked: they describe the
    # maintainer's machine, which CI cannot see.
    import collections
    kinds = collections.Counter(r["kind"] for r in man.get("skills", []))
    declared = man.get("counts", {})
    for key, actual in (("vendored", kinds["vendored"]),
                        ("external", kinds["external"]),
                        ("external_unverified", kinds["external-unverified"])):
        if key in declared and declared[key] != actual:
            out.append(f"manifest: counts.{key}={declared[key]} but {actual} entries have that kind")
    on_disk = len([d for d in os.listdir(os.path.join(ROOT, "skills"))
                   if os.path.isdir(os.path.join(ROOT, "skills", d))])
    if declared.get("vendored") not in (None, on_disk):
        out.append(f"manifest: counts.vendored={declared['vendored']} but {on_disk} dirs in skills/")

    # Publication mode lives in policy.yml. The manifest may restate the totals; it may not disagree.
    pub = man.get("publication", {})
    if pub:
        if pub.get("authority") != "publish/policy.yml":
            out.append("manifest: publication.authority must name publish/policy.yml")
        for key, names in (("generated", _generated_names(pol)),
                           ("public_authored", _public_authored_names(pol))):
            if key in pub and pub[key] != len(names):
                out.append(f"manifest: publication.{key}={pub[key]} but policy has {len(names)}")
    return out

def cmd_check(pol):
    changes, current, problems = plan(pol)
    problems = problems + validate_manifest(pol)
    drift = [n for n, _, _, _ in changes]
    if drift:
        print(f"DRIFT: {len(drift)} generated skill(s) differ from policy+source:")
        for n in drift: print("  -", n)
    if problems:
        print(f"PROBLEMS: {len(problems)}")
        for p in problems: print("  !", p)
    if not drift and not problems:
        print(f"clean: {len(current)} generated current, "
              f"{len(_public_authored_names(pol))} public-authored validated")
        return 0
    return 1

def main(argv=None):
    ap = argparse.ArgumentParser(prog="publish-skills")
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--dry-run", action="store_true")
    g.add_argument("--apply", action="store_true")
    g.add_argument("--check", action="store_true")
    g.add_argument("--verify-public", action="store_true",
                   help="CI-safe: validate this repo only; never reads private canonical sources")
    ap.add_argument("--policy", default=POLICY)
    ap.add_argument("--no-diff", action="store_true")
    a = ap.parse_args(argv)
    try:
        pol = load_policy(a.policy)
        if a.apply:  return cmd_apply(pol)
        if a.check:  return cmd_check(pol)
        if a.verify_public: return cmd_verify_public(pol)
        return cmd_dry_run(pol, show_diff=not a.no_diff)
    except Failure as e:
        print("FAIL:", e); return 2

if __name__ == "__main__":
    sys.exit(main())
