#!/usr/bin/env python3
"""Deterministic publisher for agent-skills.

Three modes, all driven by publish/policy.yml:

  --dry-run   report exactly what would change, write nothing   (default)
  --apply     write generated skills only
  --check     fail if public output has drifted from policy+source

Public-authored skills are never generated. That is enforced structurally: `_generated_names()`
is the only source of write targets, and `_assert_writable()` re-checks every path before a write.
"""
from __future__ import annotations
import argparse, difflib, hashlib, os, re, stat, sys
import yaml
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from transforms import apply_all

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
POLICY = os.path.join(ROOT, "publish", "policy.yml")
LOCK = os.path.join(ROOT, "publish", "generated.lock")

# --- privacy gate: explicit, narrow, and NOT a proof of absence -------------------------
SECRET_PATTERNS = [
    (r"/Users/courtneyrobertson", "private absolute home path"),
    (r"\bCourtney\b", "personal name not covered by policy"),
    (r"\b2nd Brain\b", "private vault name"),
    (r"\bcourtneyr\.dev\b", "private domain"),
    (r"(?i)\b(api[_-]?key|secret[_-]?key|access[_-]?token|bearer)\b\s*[:=]\s*\S+", "credential-shaped assignment"),
    (r"-----BEGIN [A-Z ]*PRIVATE KEY-----", "private key block"),
    (r"\bgh[pousr]_[A-Za-z0-9]{16,}", "GitHub token"),
    (r"\bsk-[A-Za-z0-9]{20,}", "API key"),
    (r"<!--\s*private\s*-->", "explicit private marker"),
]

class Failure(Exception): pass

def load_policy(path=POLICY):
    with open(path) as f:
        pol = yaml.safe_load(f)
    for name, spec in pol["skills"].items():
        if spec.get("mode") not in ("generated", "public-authored"):
            raise Failure(f"policy: {name} has no valid mode (fail closed)")
    return pol

def canonical_root(pol):
    raw = pol["canonical_root"]
    m = re.match(r"\$\{(\w+):-(.+)\}", raw)
    if m:
        raw = os.environ.get(m.group(1)) or m.group(2)
    return os.path.expanduser(raw)

def _generated_names(pol):
    return sorted(n for n, s in pol["skills"].items() if s["mode"] == "generated")

def _public_authored_names(pol):
    return sorted(n for n, s in pol["skills"].items() if s["mode"] == "public-authored")

def _assert_writable(pol, name):
    """Structural guard. Called immediately before every write."""
    if pol["skills"][name]["mode"] != "generated":
        raise Failure(f"REFUSED: {name} is {pol['skills'][name]['mode']}; generator must never write it")

def public_path(pol, name):
    return os.path.join(ROOT, pol["public_root"], name, "SKILL.md")

def source_path(pol, name):
    spec = pol["skills"][name]
    return os.path.join(canonical_root(pol), spec.get("source", name), "SKILL.md")

def sha(text):
    return hashlib.sha256(text.encode("utf-8")).hexdigest()

def write_lock(pol):
    """Record what the publisher produced, so public CI can detect hand edits to generated files
    WITHOUT needing the private canonical sources."""
    lines = ["# Generated by publish_skills.py --apply. Do not edit by hand.",
             "# sha256 of every GENERATED public file, SKILL.md and supporting files alike.",
             "# A trailing 'x' marks an executable file. Public-authored, excluded and runtime",
             "# files are absent by design -- their absence is what protects them."]
    for name in _generated_names(pol):
        pp = public_path(pol, name)
        if os.path.exists(pp):
            lines.append(f"{name}/SKILL.md {sha(open(pp, encoding='utf-8').read())}")
    for verb, name, rel, pp, want, want_x in file_plan(pol)[0]:
        if verb in ("CURRENT", "CHANGE", "ADD") and os.path.exists(pp):
            mark = " x" if _is_exec(pp) else ""
            lines.append(f"{name}/{rel} {sha(open(pp, encoding='utf-8', errors='replace').read())}{mark}")
    lines[4:] = sorted(lines[4:])
    with open(LOCK, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

def read_lock():
    if not os.path.exists(LOCK):
        return None
    out = {}
    for line in open(LOCK, encoding="utf-8"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        out[parts[0]] = (parts[1], len(parts) > 2 and parts[2] == "x")
    return out

def cmd_verify_public(pol):
    """CI-safe. Uses only files in this repository -- never the private canonical sources.

    Proves: every skill has a declared mode; public-authored files exist and are NOT under
    generator control; every generated artifact matches the lock recorded at publish time.
    Does NOT prove canonical drift -- that needs the private sources and stays local-only.
    """
    problems = []
    lock = read_lock()
    if lock is None:
        return _report("verify-public", ["publish/generated.lock missing -- run --apply locally"])
    for name in _public_authored_names(pol):
        if not os.path.exists(public_path(pol, name)):
            problems.append(f"{name}: public-authored file missing")
        if f"{name}/SKILL.md" in lock:
            problems.append(f"{name}: public-authored but present in generated.lock (would be overwritten)")
    for name in _generated_names(pol):
        pp = public_path(pol, name)
        key = f"{name}/SKILL.md"
        if not os.path.exists(pp):
            problems.append(f"{name}: generated artifact missing"); continue
        if key not in lock:
            problems.append(f"{name}: generated but absent from lock -- republish locally"); continue
        if sha(open(pp, encoding="utf-8").read()) != lock[key][0]:
            problems.append(f"{name}: generated artifact edited by hand (lock mismatch)")

    # Complete-artifact integrity, still using only files in this repository.
    n_gen_files = n_pa_files = 0
    for name in _generated_names(pol):
        modes = supporting_modes(pol, name)
        pub_dir = skill_public_dir(pol, name)
        present = _walk_rel(pub_dir)
        for rel in sorted(set(modes) | present):
            key, mode, pp = f"{name}/{rel}", modes.get(rel), os.path.join(pub_dir, rel)
            if mode is None:
                problems.append(f"{key}: in the public tree but not declared in policy")
            elif mode == "excluded":
                if rel in present:
                    problems.append(f"{key}: declared excluded but present in the public tree")
                if key in lock:
                    problems.append(f"{key}: excluded but hashed in the lock")
            elif mode == "public-authored":
                n_pa_files += 1
                if rel not in present:
                    problems.append(f"{key}: public-authored supporting file missing")
                if key in lock:
                    problems.append(f"{key}: public-authored but hashed in the lock (would be overwritten)")
            elif mode == "generated":
                n_gen_files += 1
                if rel not in present:
                    problems.append(f"{key}: generated supporting file missing"); continue
                if key not in lock:
                    problems.append(f"{key}: generated but absent from lock -- republish locally"); continue
                want_sha, want_x = lock[key]
                if sha(open(pp, encoding="utf-8", errors="replace").read()) != want_sha:
                    problems.append(f"{key}: generated supporting file edited by hand (lock mismatch)")
                elif _is_exec(pp) != want_x:
                    problems.append(f"{key}: executable bit differs from the lock")
            else:
                problems.append(f"{key}: unknown mode {mode!r}")
    problems += validate_manifest(pol)
    return _report("verify-public", problems,
                   ok=f"{len(_generated_names(pol))} generated SKILL.md + {n_gen_files} generated "
                      f"supporting files match the lock, {len(_public_authored_names(pol))} "
                      f"public-authored skills and {n_pa_files} public-authored files protected")

def _report(label, problems, ok=""):
    if problems:
        print(f"{label}: FAIL ({len(problems)})")
        for p in problems: print("  !", p)
        return 1
    print(f"{label}: clean — {ok}")
    return 0

def privacy_scan(text, name):
    hits = [why for pat, why in SECRET_PATTERNS if re.search(pat, text)]
    return [f"{name}: {h}" for h in hits]


# ---------------------------------------------------------------------------
# Complete-artifact publication.
#
# A generated skill is a DIRECTORY, not just a SKILL.md. Every supporting file needs an
# explicit mode, because the three failure modes differ:
#   generated       -> transform(canonical); hashed in the lock; overwritten by apply
#   public-authored -> hand-written for public users; apply must never touch it
#   excluded        -> private, runtime or backup; must never reach the public tree
#
# Defaults fail closed in BOTH directions. An undeclared CANONICAL file never publishes, so a
# new private file cannot leak simply by appearing on disk. An undeclared PUBLIC file is an
# error, so a stale or hand-added public file cannot hide either.
SKIP_DIRS = {"__pycache__", ".git", ".venv", "node_modules"}
SKIP_FILES = {".DS_Store"}

def _sf_defaults(pol):
    return pol["defaults"].get("supporting_files", {})

def supporting_modes(pol, name):
    return dict(pol["skills"][name].get("files") or {})

def skill_public_dir(pol, name):
    return os.path.join(ROOT, pol["public_root"], name)

def skill_source_dir(pol, name):
    return os.path.join(canonical_root(pol), pol["skills"][name].get("source", name))

def _walk_rel(base):
    """Relative paths of every supporting file under base (SKILL.md and caches excluded)."""
    out = set()
    if not os.path.isdir(base):
        return out
    for r, d, fs in os.walk(base):
        d[:] = [x for x in d if x not in SKIP_DIRS]
        for f in fs:
            if f in SKIP_FILES or (r == base and f == "SKILL.md"):
                continue
            out.add(os.path.relpath(os.path.join(r, f), base))
    return out

def _is_exec(path):
    return bool(os.stat(path).st_mode & stat.S_IXUSR)

def render_file(pol, name, rel):
    """Transform one canonical supporting file. Same named transforms as SKILL.md -- there is
    deliberately no second transform implementation."""
    src = os.path.join(skill_source_dir(pol, name), rel)
    if os.path.islink(src):
        raise Failure(f"{name}/{rel}: canonical file is a symlink; publication has no symlink policy")
    if not os.path.exists(src):
        raise Failure(f"{name}/{rel}: declared generated but canonical source is missing")
    spec = pol["skills"][name]
    with open(src, "rb") as f:
        raw = f.read()
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        raise Failure(f"{name}/{rel}: not UTF-8; no binary publication policy exists")
    out = apply_all(text, spec.get("transforms", pol["defaults"]["transforms"]))
    if not out.endswith("\n"):
        out += "\n"
    return out, _is_exec(src)

def file_plan(pol):
    """Per-file actions across every generated skill. Never writes.

    Returns (actions, problems) where each action is
    (verb, skill, rel, public_path, want_text_or_None, want_exec_or_None).
    """
    actions, problems = [], []
    undeclared_public = _sf_defaults(pol).get("undeclared_public", "blocked")
    for name in _generated_names(pol):
        modes = supporting_modes(pol, name)
        pub_dir, src_dir = skill_public_dir(pol, name), skill_source_dir(pol, name)
        pub_files, src_files = _walk_rel(pub_dir), _walk_rel(src_dir)
        for rel in sorted(set(modes) | pub_files | src_files):
            mode = modes.get(rel)
            pp = os.path.join(pub_dir, rel)
            if mode is None:
                # Undeclared. Present publicly -> error. Canonical-only -> silently not published.
                if rel in pub_files and undeclared_public == "blocked":
                    problems.append(f"{name}/{rel}: present in the public tree but not declared in policy")
                    actions.append(("BLOCK", name, rel, pp, None, None))
                continue
            if mode == "excluded":
                if rel in pub_files:
                    problems.append(f"{name}/{rel}: declared excluded but present in the public tree")
                    actions.append(("BLOCK", name, rel, pp, None, None))
                else:
                    actions.append(("EXCLUDE", name, rel, pp, None, None))
                continue
            if mode == "public-authored":
                if rel not in pub_files:
                    problems.append(f"{name}/{rel}: public-authored file missing")
                actions.append(("PROTECT", name, rel, pp, None, None))
                continue
            if mode != "generated":
                problems.append(f"{name}/{rel}: unknown mode {mode!r}")
                actions.append(("BLOCK", name, rel, pp, None, None))
                continue
            try:
                want, want_x = render_file(pol, name, rel)
            except Failure as e:
                problems.append(str(e))
                actions.append(("BLOCK", name, rel, pp, None, None))
                continue
            leaks = privacy_scan(want, f"{name}/{rel}")
            if leaks:
                problems.extend(leaks)
                actions.append(("BLOCK", name, rel, pp, None, None))
                continue
            if os.path.exists(pp):
                have = open(pp, encoding="utf-8", errors="replace").read()
                if have == want and _is_exec(pp) == want_x:
                    actions.append(("CURRENT", name, rel, pp, want, want_x))
                else:
                    actions.append(("CHANGE", name, rel, pp, want, want_x))
            else:
                actions.append(("ADD", name, rel, pp, want, want_x))
    return actions, problems

def render(pol, name):
    src = source_path(pol, name)
    if not os.path.exists(src):
        raise Failure(f"{name}: canonical source missing at {src}")
    spec = pol["skills"][name]
    transforms = spec.get("transforms", pol["defaults"]["transforms"])
    with open(src, encoding="utf-8") as f:
        text = f.read()
    # Declarative, per-skill line removal. Explicit substrings only -- never a heuristic.
    omit = spec.get("omit_lines_containing", [])
    if omit:
        text = "\n".join(l for l in text.split("\n") if not any(o in l for o in omit))
    out = apply_all(text, transforms)
    if not out.endswith("\n"):
        out += "\n"
    return out

def plan(pol):
    """Returns (changes, current, problems). Never writes."""
    changes, current, problems = [], [], []
    for name in _generated_names(pol):
        try:
            want = render(pol, name)
        except Failure as e:
            problems.append(str(e)); continue
        leaks = privacy_scan(want, name)
        if leaks:
            problems.extend(leaks); continue
        pp = public_path(pol, name)
        have = open(pp, encoding="utf-8").read() if os.path.exists(pp) else None
        if have == want:
            current.append(name)
        else:
            changes.append((name, have, want, pp))
    for name in _public_authored_names(pol):
        pp = public_path(pol, name)
        if not os.path.exists(pp):
            problems.append(f"{name}: public-authored file missing at {pp}")
    return changes, current, problems

def cmd_dry_run(pol, show_diff=True):
    changes, current, problems = plan(pol)
    print(f"generated considered : {len(_generated_names(pol))}")
    print(f"  already current    : {len(current)}")
    print(f"  would change/add   : {len(changes)}")
    print(f"public-authored PROTECTED (never generated): {len(_public_authored_names(pol))}")
    for n in _public_authored_names(pol):
        print(f"    skip {n}")
    if show_diff:
        for name, have, want, pp in changes:
            rel = os.path.relpath(pp, ROOT)
            a = (have or "").splitlines(keepends=True)
            print(f"\n--- would {'add' if have is None else 'change'}: {rel}")
            for line in list(difflib.unified_diff(a, want.splitlines(keepends=True),
                                                  fromfile=f"a/{rel}", tofile=f"b/{rel}"))[:40]:
                print("   " + line.rstrip("\n"))
    facts, fproblems = file_plan(pol)
    from collections import Counter
    c = Counter(v for v, *_ in facts)
    print(f"\nsupporting files      : {len(facts)}")
    for verb in ("CHANGE", "ADD", "CURRENT", "PROTECT", "EXCLUDE", "BLOCK"):
        if c.get(verb):
            print(f"  {verb:8} {c[verb]}")
    for verb, name, rel, pp, want, want_x in facts:
        if verb in ("CHANGE", "ADD", "BLOCK"):
            print(f"    {verb:8} {name}/{rel}")
    problems = problems + fproblems
    if problems:
        print(f"\nPROBLEMS ({len(problems)}) — publication would fail closed:")
        for p in problems: print("  !", p)
    return 1 if problems else 0

def cmd_apply(pol):
    changes, current, problems = plan(pol)
    if problems:
        print("refusing to apply; unresolved problems:")
        for p in problems: print("  !", p)
        return 1
    facts, fproblems = file_plan(pol)
    if fproblems:
        print("refusing to apply; unresolved supporting-file problems:")
        for p in fproblems: print("  !", p)
        return 1
    for name, have, want, pp in changes:
        _assert_writable(pol, name)
        os.makedirs(os.path.dirname(pp), exist_ok=True)
        with open(pp, "w", encoding="utf-8") as f:
            f.write(want)
        print(f"wrote {os.path.relpath(pp, ROOT)}")
    written = 0
    for verb, name, rel, pp, want, want_x in facts:
        if verb not in ("CHANGE", "ADD"):
            continue
        _assert_writable(pol, name)
        if supporting_modes(pol, name).get(rel) != "generated":
            raise Failure(f"REFUSED: {name}/{rel} is not generated; apply must never write it")
        os.makedirs(os.path.dirname(pp), exist_ok=True)
        with open(pp, "w", encoding="utf-8") as f:
            f.write(want)
        mode = os.stat(pp).st_mode
        os.chmod(pp, mode | 0o111 if want_x else mode & ~0o111)
        print(f"wrote {os.path.relpath(pp, ROOT)}")
        written += 1
    # A canonical file that disappears does NOT delete its public output. Retirement is an
    # explicit policy act (move the entry to `retired:`), never a side effect of a missing source.
    write_lock(pol)
    print(f"wrote {os.path.relpath(LOCK, ROOT)}")
    print(f"applied: {len(changes)} SKILL.md + {written} supporting files written, "
          f"{len(current)} SKILL.md already current")
    return 0

def validate_manifest(pol):
    """Validate the hand-maintained manifest against policy. We do NOT regenerate it: it carries
    judgment (attribution, licence interpretation, private exclusion) that heuristics must not
    overwrite. The publisher only checks the facts it can derive."""
    mpath = os.path.join(ROOT, "manifest.json")
    if not os.path.exists(mpath):
        return ["manifest.json missing"]
    import json
    with open(mpath) as f:
        man = json.load(f)
    declared = {r["name"] for r in man.get("skills", []) if r.get("kind") == "vendored"}
    policied = set(pol["skills"])
    out = []
    for n in sorted(policied - declared):
        out.append(f"manifest: {n} is in policy but not declared vendored")
    for n in sorted(declared - policied):
        out.append(f"manifest: {n} declared vendored but absent from policy")
    for r in man.get("skills", []):
        if r.get("kind") == "vendored" and not r.get("redistributable", False):
            out.append(f"manifest: {r['name']} vendored but not redistributable")

    # Derivable counts must not drift. Machine-snapshot counts are NOT checked: they describe the
    # maintainer's machine, which CI cannot see.
    import collections
    kinds = collections.Counter(r["kind"] for r in man.get("skills", []))
    declared = man.get("counts", {})
    for key, actual in (("vendored", kinds["vendored"]),
                        ("external", kinds["external"]),
                        ("external_unverified", kinds["external-unverified"])):
        if key in declared and declared[key] != actual:
            out.append(f"manifest: counts.{key}={declared[key]} but {actual} entries have that kind")
    on_disk = len([d for d in os.listdir(os.path.join(ROOT, "skills"))
                   if os.path.isdir(os.path.join(ROOT, "skills", d))])
    if declared.get("vendored") not in (None, on_disk):
        out.append(f"manifest: counts.vendored={declared['vendored']} but {on_disk} dirs in skills/")

    # Publication mode lives in policy.yml. The manifest may restate the totals; it may not disagree.
    pub = man.get("publication", {})
    if pub:
        if pub.get("authority") != "publish/policy.yml":
            out.append("manifest: publication.authority must name publish/policy.yml")
        for key, names in (("generated", _generated_names(pol)),
                           ("public_authored", _public_authored_names(pol))):
            if key in pub and pub[key] != len(names):
                out.append(f"manifest: publication.{key}={pub[key]} but policy has {len(names)}")
    return out

def cmd_check(pol):
    """Local-only. Compares the COMPLETE canonical artifact against the public one.

    Public-authored files are deliberately never compared to canonical -- they are hand-written
    for public users and are expected to differ.
    """
    changes, current, problems = plan(pol)
    facts, fproblems = file_plan(pol)
    problems = problems + fproblems + validate_manifest(pol)
    drift = [n for n, _, _, _ in changes]
    fdrift = [f"{n}/{rel}" for verb, n, rel, *_ in facts if verb in ("CHANGE", "ADD")]
    if drift:
        print(f"DRIFT: {len(drift)} generated SKILL.md differ from policy+source:")
        for n in drift: print("  -", n)
    if fdrift:
        print(f"DRIFT: {len(fdrift)} generated supporting file(s) differ from policy+source:")
        for n in fdrift: print("  -", n)
    if problems:
        print(f"PROBLEMS: {len(problems)}")
        for p in problems: print("  !", p)
    if not drift and not fdrift and not problems:
        n_gen = sum(1 for v, *_ in facts if v == "CURRENT")
        n_pa = sum(1 for v, *_ in facts if v == "PROTECT")
        n_ex = sum(1 for v, *_ in facts if v == "EXCLUDE")
        print(f"clean: {len(current)} generated SKILL.md + {n_gen} generated supporting files "
              f"current, {len(_public_authored_names(pol))} public-authored skills and {n_pa} "
              f"public-authored files validated, {n_ex} excluded held back")
        return 0
    return 1

def main(argv=None):
    ap = argparse.ArgumentParser(prog="publish-skills")
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--dry-run", action="store_true")
    g.add_argument("--apply", action="store_true")
    g.add_argument("--check", action="store_true")
    g.add_argument("--verify-public", action="store_true",
                   help="CI-safe: validate this repo only; never reads private canonical sources")
    ap.add_argument("--policy", default=POLICY)
    ap.add_argument("--no-diff", action="store_true")
    a = ap.parse_args(argv)
    try:
        pol = load_policy(a.policy)
        if a.apply:  return cmd_apply(pol)
        if a.check:  return cmd_check(pol)
        if a.verify_public: return cmd_verify_public(pol)
        return cmd_dry_run(pol, show_diff=not a.no_diff)
    except Failure as e:
        print("FAIL:", e); return 2

if __name__ == "__main__":
    sys.exit(main())
